name: Build artifacts

on:
  workflow_call:

jobs:
  provide_versions_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Install gojq"
        run: 'go install github.com/itchyny/gojq/cmd/gojq@latest'
      - id: set-matrix
        run: echo "matrix=$(seq $(./count_versions.sh) | gojq -R | gojq -s -c)" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build_artifacts:
    name: Build artifacts
    needs: provide_versions_json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: ${{ fromJson(needs.provide_versions_json.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Install packwiz"
        run: 'go install github.com/packwiz/packwiz@latest'
      - name: "Build modpack by index ${{ matrix.index }}"
        run: "./create_by_index.sh ${{ matrix.index }}"
      - name: "Set variables"
        id: set_vars
        run: |
          line=$(./get_version_by_index.sh ${{ matrix.index }})
          echo "minecraftVersion=$(./get_var_by_index.sh $line 1)" >> $GITHUB_OUTPUT
          echo "modpackName=$(./get_var_by_index.sh $line 3)" >> $GITHUB_OUTPUT
          echo "modpackVersion=$(./get_var_by_index.sh $line 4)" >> $GITHUB_OUTPUT
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "artifact-${{ steps.set_vars.outputs.modpackName }}_${{ steps.set_vars.outputs.modpackVersion }}-${{ steps.set_vars.outputs.minecraftVersion }}"
          path: "${{ github.workspace }}/artifacts/"
          if-no-files-found: error
      - name: "Publish modpack"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.set_vars.outputs.modpackName }} ${{ steps.set_vars.outputs.modpackVersion }}-${{ steps.set_vars.outputs.minecraftVersion }}
#          modrinth-id: RhyIK0tf
#          modrinth-featured: true
#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: '${{ github.workspace }}/artifacts/*.mrpack'
          loaders: quilt
          game-versions: ${{ steps.set_vars.outputs.minecraftVersion }}

