name: Build artifacts

on:
  workflow_call:

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Install packwiz"
        run: 'go install github.com/packwiz/packwiz@latest'
      - name: "Build modpacks"
        run: "./create_batch.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: "${{ github.workspace }}/artifacts/"
          if-no-files-found: error
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: RhyIK0tf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: '${{ github.workspace }}/artifacts/*.mrpack'

