name: Build artifacts

on:
  workflow_call:

jobs:
  provide_versions_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: versions
        with:
          cmd: 'seq $(./count_versions.sh) | jq -R | jq -s'
      - id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.versions.outputs.matrix }}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build_artifacts:
    name: Build artifacts
    needs: provide_versions_json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: ${{ fromJson(needs.provide_versions_json.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: "Install packwiz"
        run: 'go install github.com/packwiz/packwiz@latest'
      - name: "Build modpack by index ${{ matrix.index }}"
        run: "./create_by_index.sh ${{ matrix.index }}"
      - name: "Set variables"
        id: set_vars
        run: |
          line=$(./get_version_by_index.sh ${{ matrix.index }})
          echo "::set-output minecraftVersion=::$(./get_var_by_index.sh $line 1)"
          echo "::set-output modpackName=::$(./get_var_by_index.sh $line 3)"
          echo "::set-output modpackVersion=::$(./get_var_by_index.sh $line 4)"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "artifact-${{ steps.set_vars.outputs.modpackName }}_${{ steps.set_vars.outputs.modpackVersion }}-${{ vars.minecraftVersion }}"
          path: "${{ github.workspace }}/artifacts/"
          if-no-files-found: error
      - name: "Publish ${{ steps.set_vars.outputs.modpackName }} ${{ steps.set_vars.outputs.modpackVersion }}-${{ vars.minecraftVersion }}"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.set_vars.outputs.modpackName }} ${{ steps.set_vars.outputs.modpackVersion }}-${{ vars.minecraftVersion }}
#          modrinth-id: RhyIK0tf
#          modrinth-featured: true
#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: '${{ github.workspace }}/artifacts/*.mrpack'
          loaders: quilt
          game-versions: ${{ vars.MC_VERSION }}

